backend/models/BtsItem.php
<?php

namespace backend\models;

use Yii;

class BtsItem extends \common\models\BtsItemBase {

    public function rules()
    {
        return [
            [['name', 'category_id', 'group_id', 'image_num'], 'required'],
            [['category_id', 'created_by', 'updated_by', 'image_num'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['name', 'image_path'], 'string', 'max' => 255],
            [['status'], 'string', 'max' => 1],
            [['note'], 'string', 'max' => 2000],
            ['name', 'unique'],
        ];
    }
}

backend/controllers/BtsItemController.php
<?php

namespace backend\controllers;

use common\helpers\FileHelper;
use common\helpers\Helpers;
use Yii;
use backend\models\BtsItem;
use backend\models\BtsItemSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Inflector;
use yii\helpers\StringHelper;
use common\components\slim\Slim;

/**
 * BtsItemController implements the CRUD actions for BtsItem model.
 */
class BtsItemController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all BtsItem models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BtsItemSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single BtsItem model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        if (Yii::$app->request->isAjax) {
            $this->layout = false;
        }
        return $this->render('view', [
            'model' => $this->findModel($id),
            'isAjax' => Yii::$app->request->isAjax,
        ]);
    }

    /**
     * Creates a new BtsItem model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new BtsItem();
        $model->image_num = 1;
        $model->status = 1;

        $modelClassName =  Inflector::camel2words(StringHelper::basename($model::className()));

        $form_values = Yii::$app->request->post();
        // Lay du lieu anh upload len de validate
        // Neu ko co thi xoa
        $imageFieldName = 'image_path';
        $form_values[$imageFieldName] = Slim::getImagesFromSlimRequest($imageFieldName);
        if ($model->load($form_values) && $model->save()) {
            FileHelper::processUploadNewImage($model, $imageFieldName);

            Yii::$app->session->setFlash('info', Yii::t('backend', 'Thêm mới "{object}" thành công!', ['object' => Yii::t('backend', $modelClassName)]));

            // bo sung redirect
            if (Yii::$app->request->post('save_and_back')) {
                return $this->redirect(['index']);
            } elseif (Yii::$app->request->post('save_and_add')) {
                return $this->redirect(['create']);
            } else {
                return $this->redirect(['update', 'id' => $model->id]);
            }

        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }


    }

    /**
     * Updates an existing BtsItem model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $modelClassName =  Inflector::camel2words(StringHelper::basename($model::className()));

        $model->loadDefaultValues();
        $form_values = Yii::$app->request->post();

        // Lay du lieu anh upload len de validate
//        $imageFieldName = 'image_path';
//        $form_values[$imageFieldName] = Slim::getImagesFromSlimRequest($imageFieldName);

        if ($model->load($form_values) && $model->save()) {

//            FileHelper::processUpdateImage($model, $form_values, $imageFieldName);

            Yii::$app->session->setFlash('info', Yii::t('backend', 'Chỉnh sửa {object} thành công!', ['object' => Yii::t('backend', $modelClassName)]));

            // bo sung redirect
            if (Yii::$app->request->post('save_and_back')) {
                return $this->redirect(['index']);
            } elseif (Yii::$app->request->post('save_and_add')) {
                return $this->redirect(['create']);
            } else {
                 return $this->redirect(['index']);
            }
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing BtsItem model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $modelClassName =  Inflector::camel2words(StringHelper::basename($model::className()));
        $model->delete();

        Yii::$app->session->setFlash('info', Yii::t('backend', 'Xóa {object} thành công!', ['object' => Yii::t('backend', $modelClassName)]));

        return $this->redirect(['index']);
    }

    /**
     * Finds the BtsItem model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return BtsItem the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = BtsItem::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionGetActiveItemsByCate()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $params = Yii::$app->request->post('depdrop_all_params');
        $data = [];
        if (isset($params['item-cate-id'])) {
            $data = BtsItem::getActiveItemsArrByCate($params['item-cate-id']);

            $data = array_values($data);
            //$data = Helpers::array_change_key_case_recursive($data, CASE_LOWER);

        }


        return ['output'=> $data, 'selected'=> Yii::$app->request->get('selected')];
    }

}

backend/views/bts-item/_form.php
<?php

use yii\helpers\Html;
use \yii\widgets\ActiveForm;
use kartik\widgets\Select2;
use yii\helpers\StringHelper;
use yii\helpers\Inflector;
use kartik\widgets\DepDrop;

/* @var $this yii\web\View */
/* @var $model backend\models\BtsItem */
/* @var $title string */
/* @var $form ActiveForm */
?>

<?php $form = ActiveForm::begin(); ?>

    <div class="portlet light portlet-fit portlet-form bordered bts-item-form">

        <div class="portlet-body">
            <div class="form-body row">
                <div class="col-md-6">
                    <?= $form->field($model, 'category_id')->widget(Select2::classname(), [
                        'data' => \yii\helpers\ArrayHelper::map(\backend\models\ItemCategory::find()->all(), 'id', 'name'),
                        'size' => Select2::MEDIUM,
                        'options' => [
                            'placeholder' => Yii::t('backend', 'Choose a category'),
                            'id' => 'category-id'
                        ],
                        'pluginOptions' => [
                            'allowClear' => true
                        ],
                        'addon' => [
                            'prepend' => [
                                'content' => '<i class="glyphicon glyphicon-search"></i>'
                            ]
                        ],
                    ]); ?>
                </div>

                <div class="col-md-6">
                    <?php

                    echo $form->field($model, 'group_id')->widget(DepDrop::classname(), [
                        'type' => DepDrop::TYPE_SELECT2,
                        'select2Options' => ['pluginOptions' => ['allowClear' => false]],
                        'data' => \yii\helpers\ArrayHelper::map(\backend\models\ItemGroup::getGroupListByCate($model->category_id), 'id', 'name'),
                        'options' => ['id' => 'group-id'],
                        'pluginOptions' => [
                            'depends' => ['category-id'],
                            //'placeholder' => Yii::t('backend', 'Choose '),
                            'url' => \yii\helpers\Url::to(['item-category/get-item-group', 'selected' => $model->group_id]),
                        ]
                    ]);
                    ?>
                </div>
                <div class="clearfix"></div>
                <div class="col-md-6">
                    <?= $form->field($model, 'name')->textInput(['maxlength' => 255]) ?>

                </div>
                <div class="col-md-6">
                    <?= $form->field($model, 'image_num')->textInput(['type' => 'number','min' =>1]) ?>
                </div>

                <div class="clearfix"></div>
                <div class="col-md-6">
                    <br/>
                    <?= $form->field($model, 'status')->checkbox() ?>

                    <?= $form->field($model, 'note')->textarea(['maxlength' => 2000, 'rows' => 4]) ?>
                </div>
                <?php /*
                <div class="col-md-6">

                    <?= $this->render('/common/_slim_image_field', [
                        'fieldName' => 'image_path',
                        'itemName' => 'item-image', // Vi du: adv, post, post-category de luu rieng tung folder
                        'fieldLabel' => Yii::t('backend', 'Image'),
                        'dataMinSize' => '0,0',
                        'dataSize' => '',
                        'dataForceSize' => '',
                        'dataRatio' => '',
                        'model' => $model,
                        'dataWillRemove' => 'imageWillChange',
                        'dataWillSave' => 'imageWillChange',
                        'dataMaxFileSize' => 0.3
                    ]) ?>
                </div>
                */ ?>
                <div class="clearfix"></div>

            </div>
        </div>
        <div class="portlet-title ">


            <a href="<?= \yii\helpers\Url::to(['index']); ?>" class="btn btn-default btn-sm">
                <i class="fa fa-angle-left"></i> <?= Yii::t('backend', 'Back') ?>                </a>
            &nbsp;&nbsp;&nbsp;
            <?= Html::submitButton($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Update'), ['class' => 'btn btn-transparent green  btn-sm']) ?>


        </div>
    </div>

<?php ActiveForm::end(); ?>
<?php \common\components\slim\SlimAsset::register($this); ?>

backend/views/bts-item/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\Select2;
/* @var $this yii\web\View */
/* @var $model backend\models\BtsItemSearch */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="panel panel-default bts-item-search">
    <div class="panel-body row">

        <?php $form = ActiveForm::begin([
            'action' => ['index'],
            'method' => 'get',
        ]); ?>

        <div class="col-md-3">
            <?= $form->field($model, 'name') ?>

        </div>
        <div class="col-md-3">

            <?= $form->field($model, 'category_id')->widget(Select2::classname(), [
                'data' => \yii\helpers\ArrayHelper::map(\backend\models\ItemCategory::find()->all(), 'id', 'name'),
                'size' => Select2::MEDIUM,
                'options' => [
                    'placeholder' => Yii::t('backend', 'All category')
                ],
                'pluginOptions' => [
                    'allowClear' => true
                ],
                'addon' => [
                    'prepend' => [
                        'content' => '<i class="glyphicon glyphicon-search"></i>'
                    ]
                ],
            ]); ?>
        </div>
        <div class="col-md-3">
            <?=
            $form->field($model, 'status')->dropDownList(
                (isset(Yii::$app->params['status'])) ? Yii::$app->params['status'] : [
                    0 => Yii::t('backend', 'Not yet ') . Yii::t('backend', 'Status'),
                    1 => Yii::t('backend', 'Status'),
                ],
                ['prompt' => Yii::t('backend', 'All')]
            );;

            ?>

        </div>
        <div class="col-md-3">
            <?=

            $form->field($model, 'created_at')->widget(\kartik\daterange\DateRangePicker::className(), [
                    'options' => ['class' => 'form-control daterange-field input-sm'],
                    'model' => $model,
                    'attribute' => 'created_at',
                    'convertFormat' => true,
                    'presetDropdown' => true,
                    'readonly' => true,
                    'pluginOptions' => [
                        'opens' => 'left',
                        'alwaysShowCalendars' => true,
                        'timePickerIncrement' => 30,
                        'locale' => [
                            'format' => 'd/m/Y',
                        ]
                    ],
                    'pluginEvents' => [
                        'cancel.daterangepicker' => "function(ev, picker) {
                                            $(this).val('');
                                        }",
                        'apply.daterangepicker' => 'function(ev, picker) {
                                            if($(this).val() == "") {
                                                $(this).val(picker.startDate.format(picker.locale.format) + picker.locale.separator +
                                                picker.endDate.format(picker.locale.format)).trigger("change");
                                            }
                                        }',
                        'show.daterangepicker' => 'function(ev, picker) {
                                            picker.container.find(".ranges").off("mouseenter.daterangepicker", "li");
                                            if($(this).val() == "") {
                                                picker.container.find(".ranges .active").removeClass("active");
                                            }
                                        }',
                    ]
                ]
            )
            ?>

        </div>
        <div class="col-md-12">
            <div class="form-group">
                <?= Html::submitButton(Yii::t('backend', 'Search'), ['class' => 'btn btn-primary']) ?>
                &nbsp;&nbsp;&nbsp;
                <?= Html::a(Yii::t('backend', 'Reset'), ['index'], ['class' => 'btn btn-default']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

backend/views/bts-item/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\BtsItem */

$this->title = Yii::t('backend', 'Create {modelClass}', [
    'modelClass' => 'Bts Item',
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Bts Items'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row bts-item-create">
    <div class="col-md-12">
        <?= $this->render('_form', [
            'model' => $model,
            'title' => $this->title
        ]) ?>
    </div>
</div>

backend/views/bts-item/index.php
<?php


use \yii\grid\GridView;
use awesome\backend\widgets\AwsBaseHtml;
use yii\helpers\Html;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\BtsItemSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('backend', 'Items');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row bts-item-index">
    <div class="col-md-12">
        <div class="portlet light portlet-fit portlet-datatable bordered">
            <div class="portlet-title">
                <?php echo $this->render('_search', ['model' => $searchModel]); ?>

                <div class="">
                    <?= Html::a(Yii::t('backend', 'Create {modelClass}', [
                        'modelClass' => Yii::t('backend', 'Item')
                    ]),
                        ['create'], ['class' => 'btn btn-info btn-sm']) ?>
                </div>
            </div>

            <div class="portlet-body">
                <div class="table-container">
                    <?php
                    Pjax::begin(['formSelector' => 'form', 'enablePushState' => false, 'id' => 'mainGridPjax']);
                    ?>

                    <?= GridView::widget([
                        'dataProvider' => $dataProvider,
                        'filterSelector' => 'select[name="per-page"]',
                        'layout' => "{items}\n <div class='form-inline pagination page-size'>" . awesome\backend\grid\AwsPageSize::widget([
                                'options' => [
                                    'class' => 'form-control  form-control-sm',
                                ]]) . '</div> <div class="col-md-6">{pager}</div> <div class="pagination col-md-3 text-right total-count">' . Yii::t('backend', 'Tổng số') . ': <b>' . number_format($dataProvider->getTotalCount()) . '</b> ' . Yii::t('backend', 'bản ghi') . '</div>',
                        // 'filterModel' => $searchModel,
                        'columns' => [
                            //['class' => 'yii\grid\SerialColumn'],

//                            [
//                                'attribute' => 'image_path',
//                                'value' => function ($model) {
//                                    return $model->getImagePathUrl();
//                                },
//                                'format' => ['image', ['height' => '50', 'onerror' => "this.src='" . Yii::$app->params['no_image'] . "';"]],
//                                'filter' => false,
//                                'headerOptions' => ['style' => 'width:120px'],
//                            ],
                            [
                                'attribute' => 'name',
                                'format' => 'raw',
                                'value' => function ($model) {
                                    return Html::a(Html::encode($model->name), ['bts-item/update', 'id' => $model->id,]);
                                },
                            ],

                            [
                                'attribute' => 'category_id',
                                'value' => function($model) {
                                    return ($model->category)? $model->category->name: null;
                                }
                            ],
                            [
                                'attribute' => 'group_id',
                                'value' => function($model) {
                                    return ($model->group)? $model->group->name: null;
                                }
                            ],
                            'image_num:integer',
                            [
                                'attribute' => 'status',
                                'format' => 'raw',
                                'value' => function ($object) {
                                    $class = ($object->status == 1) ? 'glyphicon-ok' : 'glyphicon-remove';
                                    return '<span class="glyphicon ' . $class . ' icon-is_active"></span>';
                                }
                            ],

                            'created_at',
                            //'updated_at',

                            [
                                'class' => 'yii\grid\ActionColumn',
                                'headerOptions' => ['style' => 'width: 110px;', 'class' => 'head-actions'],
                                'contentOptions' => ['class' => 'row-actions'],
                                'buttons' => [
                                    'view' => function ($url, $model) {
                                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', ['view', 'id' => $model->id], [
                                            'class' => '',
                                            'data-target' => '#detail-modal',
                                            'data-toggle' => "modal"
                                        ]);
                                    },
                                ]
                            ],
                        ],
                    ]); ?>

                    <?php
                    Pjax::end();
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div id="detail-modal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">

        </div>

    </div>
</div>

backend/views/bts-item/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\BtsItem */

$this->title = Yii::t('backend', 'Update {modelClass}: ', [
    'modelClass' => 'Bts Item',
]) . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Bts Items'), 'url' => ['index']];
//$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('backend', 'Update') . ' ' . $model->name;
?>
<div class="row bts-item-update">
    <div class="col-md-12">

    <?= $this->render('_form', [
        'model' => $model,
        'title' => $this->title
    ]) ?>

    </div>
</div>

backend/views/bts-item/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\BtsItem */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Bts Items'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row bts-item-view">
    <div class="col-md-12">
        <div class="portlet light portlet-fit portlet-datatable bordered">
            <?php if (!$isAjax): ?>
                <div class="portlet-title">

                    <div class="">
                        <?= Html::a(Yii::t('backend', 'Update'), ['update', 'id' => $model->id],
                            ['class' => 'btn btn-info  btn-sm'])
                        ?>
                        <?= Html::a(Yii::t('backend', 'Delete'), ['delete', 'id' => $model->id], [
                            'class' => 'btn btn-transparent red  btn-sm',
                            'data' => [
                                'confirm' => Yii::t('backend', 'Are you sure you want to delete this item?'),
                                'method' => 'post',
                            ],
                        ])
                        ?>
                    </div>
                </div>
            <?php endif; ?>
            <div class="portlet-body">
                <?= DetailView::widget([
                    'model' => $model,
                    'attributes' => [
                        'id',
//                        [
//                            'attribute' => 'image_path',
//                            'value' => function ($model) {
//                                return $model->getImagePathUrl();
//                            },
//                            'format' => ['image', ['height' => '80', 'onerror' => "this.src='" . Yii::$app->params['no_image'] . "';"]],
//                            'headerOptions' => ['style' => 'width:120px'],
//                        ],
                        'name',
                        [
                            'attribute' => 'category_id',
                            'value' => function($model) {
                                return ($model->category)? $model->category->name: null;
                            }
                        ],
                        [
                            'attribute' => 'group_id',
                            'value' => function($model) {
                                return ($model->group)? $model->group->name: null;
                            }
                        ],
                        'image_num:integer',
                        [
                            'attribute' => 'status',
                            'format' => 'raw',
                            'value' => function ($object) {
                                $class = ($object->status == 1) ? 'glyphicon-ok' : 'glyphicon-remove';
                                return '<span class="glyphicon ' . $class . ' icon-is_active"></span>';
                            }
                        ],
                        'note',
                        'created_at',
                        'updated_at',
                        [
                            'attribute' => 'created_by',
                            'value' => function($model) {
                                return ($model->created)? $model->created->username: null;
                            }
                        ],
                        [
                            'attribute' => 'updated_by',
                            'value' => function($model) {
                                return ($model->updated)? $model->updated->username: null;
                            }
                        ]
                    ],
                ]) ?>
            </div>
        </div>
    </div>
</div>