backend/models/Branch.php
<?php

namespace backend\models;

use Yii;
use yii\helpers\ArrayHelper;

class Branch extends \common\models\BranchBase {

    public $selected_partners  = [];

    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'unique'],
            [['created_at', 'updated_at', 'selected_partners'], 'safe'],
            [['name'], 'string', 'max' => 255],
            [['description'], 'string', 'max' => 1000],
            [['ho_user_id'],'integer']
        ];
    }

    public function loadDefaultValues($skipIfSet = true) {
        if (!$this->isNewRecord) {
            $this->selected_partners = ArrayHelper::map($this->getPartnerIds(), 'partner_id', 'partner_id');

        }

        return parent::loadDefaultValues($skipIfSet);
    }

    public function save($runValidation = true, $attributeNames = NULL) {


        if(!$this->isNewRecord) {
            $currentPartners = $this->getPartnerIds();

            if (count($currentPartners)) {
                foreach ($currentPartners as $index => $partner) {

                    // Neu truoc do da chon --> xoa bot di
                    $exists = false;
                    if (is_array($this->selected_partners) && count($this->selected_partners)) {
                        foreach ($this->selected_partners as $selectedId) {
                            if($selectedId == $partner->partner_id) {
                                $exists = true;
                                break;
                            }
                        }

                        // neu bo chon --> xoa di
                        if($exists === false) {
                            Yii::info ( "DELETE BRANCH_ID: " . $this->id . " PARTNER_ID: " . $partner->partner_id, "log_debug" );
                            BranchPartner::deleteAll([
                                'branch_id' => $this->id,
                                'partner_id' => $partner->partner_id,
                            ]);
                        }
                    } else {
                        Yii::info ( "DELETE BRANCH_ID : " . $this->id, "log_debug" );
                        BranchPartner::deleteAll([
                            'branch_id' => $this->id,
                        ]);
                    }

                }
            }

            // them nhung partner moi
            if (is_array($this->selected_partners) && count($this->selected_partners)) {
                foreach ($this->selected_partners as $item) {
                    // tag co san
                    $exists = false;

                    foreach ($currentPartners as $partner) {
                        if($partner->partner_id == $item) {
                            $exists = true;
                            break;
                        }
                    }

                    // neu post chua co tag nay thi gan tag nay vao post
                    if($exists === false) {
                        $tag = new BranchPartner();
                        $tag->branch_id = $this->id;
                        $tag->partner_id = $item;
                        $tag->save();
                    }

                }
            }


            return parent::save($runValidation, $attributeNames);

        } else {
            $return = parent::save($runValidation, $attributeNames);
            if (is_array($this->selected_partners) && count($this->selected_partners)) {
                foreach ($this->selected_partners as $item) {
                    // tag co san
                    if ($item) {
                        $tag = new BranchPartner();
                        $tag->branch_id = $this->id;
                        $tag->partner_id = $item;
                        $tag->save();
                    }
                }
            }

            return $return;
        }
    }

    public function getPartnerIds()
    {
        return BranchPartner::find()
            ->select('partner_id')
            ->where(
                ['branch_id' => $this->id]
            )
            ->all();
    }

    public function getPartners() {
        return $this->hasMany(Partner::className(), ['id' => 'partner_id'])
            ->viaTable('branch_partner', ['branch_id' => 'id'])
            ->orderBy('name asc')
            ;
    }

    public static function getBranchArray() {
        $itemArr = self::find()
            ->select('id, name')
            ->asArray()
            ->orderBy('name asc')
            ->all();

        if (!empty($itemArr)) {
            return  \yii\helpers\ArrayHelper::map($itemArr, 'id', 'name');

        } else {
            return array();
        }
    }
}

backend/controllers/BranchController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Branch;
use backend\models\BranchSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Inflector;
use yii\helpers\StringHelper;
use common\components\slim\Slim;

/**
 * BranchController implements the CRUD actions for Branch model.
 */
class BranchController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Branch models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BranchSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Branch model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        if (Yii::$app->request->isAjax) {
            $this->layout = false;
        }
        return $this->render('view', [
            'model' => $this->findModel($id),
            'isAjax' => Yii::$app->request->isAjax,
        ]);
    }

    /**
     * Creates a new Branch model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Branch();
        $modelClassName =  Inflector::camel2words(StringHelper::basename($model::className()));

        $form_values = Yii::$app->request->post();
        // Lay du lieu anh upload len de validate

        if ($model->load($form_values) && $model->save()) {


            Yii::$app->session->setFlash('info', Yii::t('backend', 'Thêm mới "{object}" thành công!', ['object' => Yii::t('backend', $modelClassName)]));

            // bo sung redirect
            if (Yii::$app->request->post('save_and_back')) {
                return $this->redirect(['index']);
            } elseif (Yii::$app->request->post('save_and_add')) {
                return $this->redirect(['create']);
            } else {
                return $this->redirect(['update', 'id' => $model->id]);
            }

        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }


    }

    /**
     * Updates an existing Branch model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $modelClassName =  Inflector::camel2words(StringHelper::basename($model::className()));

        $model->loadDefaultValues();
        $form_values = Yii::$app->request->post();

        if ($model->load($form_values) && $model->save()) {

            Yii::$app->session->setFlash('info', Yii::t('backend', 'Chỉnh sửa {object} thành công!', ['object' => Yii::t('backend', $modelClassName)]));

            // bo sung redirect
            if (Yii::$app->request->post('save_and_back')) {
               $this->redirect(['index']);
            } elseif (Yii::$app->request->post('save_and_add')) {
                return $this->redirect(['create']);
            } else {
//                return $this->redirect(['update', 'id' => $model->id]);
                return $this->redirect(['index']);
            }
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Branch model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $modelClassName =  Inflector::camel2words(StringHelper::basename($model::className()));
        $model->delete();

        Yii::$app->session->setFlash('info', Yii::t('backend', 'Xóa {object} thành công!', ['object' => Yii::t('backend', $modelClassName)]));

        return $this->redirect(['index']);
    }

    /**
     * Finds the Branch model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Branch the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Branch::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/branch/_form.php
<?php

use yii\helpers\Html;
use \yii\widgets\ActiveForm;
use yii\helpers\StringHelper;
use yii\helpers\Inflector;
use kartik\widgets\Select2;

/* @var $this yii\web\View */
/* @var $model backend\models\Branch */
/* @var $title string */
/* @var $form ActiveForm */
?>

<?php $form = ActiveForm::begin(); ?>

<div class="portlet light portlet-fit portlet-form bordered branch-form">

    <div class="portlet-body">
        <div class="form-body row">
            <div class="col-md-6">
                <?= $form->field($model, 'name')->textInput(['maxlength' => 255]) ?>

            </div>

            <div class="col-md-6">
                <?= $form->field($model, 'description')->textarea(['maxlength' => 1000, 'rows' => 4]) ?>

            </div>
            <div class="col-md-12">

                <br />
                <?php echo $form->field($model, 'selected_partners', [
                    'template' => '<div class="form-group"><label class="control-label">{label}</label>
                    <a style="margin-left: 50px" target="_blank" href="'. \yii\helpers\Url::to(['partner/index']). '">#'. Yii::t('backend', 'Partner management'). '</a>
                    {input}</div>',
                ])->widget(Select2::classname(), [

                    'data' => \backend\models\Partner::getPartnerArray(),
                    //'maintainOrder' => true,
                    'theme' => Select2::THEME_BOOTSTRAP,
                    'language' => Yii::$app->language,
                    'options' => [
                        'placeholder' => Yii::t('backend', 'Choose Partners'),
                        'multiple' => true,
                    ],
//                    'pluginOptions' => [
//                        'tags' => true,
//                        'tokenSeparators' => [','],
//                        'maximumInputLength' => 20
//                    ],
                ]); ?>
            </div>
        </div>
    </div>
    <div class="portlet-title ">


        <a href="<?= \yii\helpers\Url::to(['index']); ?>" class="btn btn-default btn-sm">
            <i class="fa fa-angle-left"></i> <?= Yii::t('backend', 'Back') ?>                </a>
        &nbsp;&nbsp;&nbsp;
        <?= Html::submitButton($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Update'), ['class' => 'btn btn-transparent green  btn-sm']) ?>


    </div>
</div>

<?php ActiveForm::end(); ?>

backend/views/branch/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\BranchSearch */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="panel panel-default branch-search">
    <div class="panel-body row">

        <?php $form = ActiveForm::begin([
            'action' => ['index'],
            'method' => 'get',
        ]); ?>

        <div class="col-md-3">
            <?= $form->field($model, 'name') ?>

        </div>
        <div class="col-md-12">
            <div class="form-group">
                <?= Html::submitButton(Yii::t('backend', 'Search'), ['class' => 'btn btn-primary']) ?>
                &nbsp;&nbsp;&nbsp;
                <?= Html::a(Yii::t('backend', 'Reset'), ['index'], ['class' => 'btn btn-default']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

backend/views/branch/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Branch */

$this->title = Yii::t('backend', 'Create {modelClass}', [
    'modelClass' => 'Branch',
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Branches'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row branch-create">
    <div class="col-md-12">
        <?= $this->render('_form', [
            'model' => $model,
            'title' => $this->title
        ]) ?>
    </div>
</div>

backend/views/branch/index.php
<?php


use \yii\grid\GridView;
use awesome\backend\widgets\AwsBaseHtml;
use yii\helpers\Html;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\BranchSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('backend', 'Branches');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row branch-index">
    <div class="col-md-12">
        <div class="portlet light portlet-fit portlet-datatable bordered">
            <div class="portlet-title">
                <?php echo $this->render('_search', ['model' => $searchModel]); ?>

                <div class="">
                    <?= Html::a(Yii::t('backend', 'Create {modelClass}', [
                        'modelClass' => Yii::t('backend', 'Branch')
                    ]),
                        ['create'], ['class' => 'btn btn-info btn-sm']) ?>
                </div>
            </div>

            <div class="portlet-body">
                <div class="table-container">
                    <?php
                    Pjax::begin(['formSelector' => 'form', 'enablePushState' => false, 'id' => 'mainGridPjax']);
                    ?>

                    <?= GridView::widget([
                        'dataProvider' => $dataProvider,
                        'filterSelector' => 'select[name="per-page"]',
                        'layout' => "{items}\n <div class='form-inline pagination page-size'>" . awesome\backend\grid\AwsPageSize::widget([
                                'options' => [
                                    'class' => 'form-control  form-control-sm',
                                ]]) . '</div> <div class="col-md-6">{pager}</div> <div class="pagination col-md-3 text-right total-count">' . Yii::t('backend', 'Tổng số') . ': <b>' . number_format($dataProvider->getTotalCount()) . '</b> ' . Yii::t('backend', 'bản ghi') . '</div>',
                        // 'filterModel' => $searchModel,
                        'columns' => [
                            //['class' => 'yii\grid\SerialColumn'],
                            'id',
                            [
                                'attribute' => 'name',
                                'format' => 'raw',
                                'value' => function ($model) {
                                    return Html::a(Html::encode($model->name), ['branch/update', 'id' => $model->id,]);
                                },
                            ],

                            'description',
                            'created_at',
                            'updated_at',

                            [
                                'class' => 'yii\grid\ActionColumn',
                                'headerOptions' => ['style' => 'width: 110px;', 'class' => 'head-actions'],
                                'contentOptions' => ['class' => 'row-actions'],
                                'buttons' => [
                                    'view' => function ($url, $model) {
                                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', ['view', 'id' => $model->id], [
                                            'class' => '',
                                            'data-target' => '#detail-modal',
                                            'data-toggle' => "modal"
                                        ]);
                                    },
                                ]
                            ],
                        ],
                    ]); ?>

                    <?php
                    Pjax::end();
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div id="detail-modal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">

        </div>

    </div>
</div>

backend/views/branch/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Branch */

$this->title = Yii::t('backend', 'Update {modelClass}: ', [
    'modelClass' => 'Branch',
]) . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Branches'), 'url' => ['index']];
//$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('backend', 'Update') . ' ' . $model->name;
?>
<div class="row branch-update">
    <div class="col-md-12">

    <?= $this->render('_form', [
        'model' => $model,
        'title' => $this->title
    ]) ?>

    </div>
</div>

backend/views/branch/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Branch */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Branches'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row branch-view">
    <div class="col-md-12">
        <div class="portlet light portlet-fit portlet-datatable bordered">
            <?php if (!$isAjax): ?>
                <div class="portlet-title">

                    <div class="">
                        <?= Html::a(Yii::t('backend', 'Update'), ['update', 'id' => $model->id],
                            ['class' => 'btn btn-info  btn-sm'])
                        ?>
                        <?= Html::a(Yii::t('backend', 'Delete'), ['delete', 'id' => $model->id], [
                            'class' => 'btn btn-transparent red  btn-sm',
                            'data' => [
                                'confirm' => Yii::t('backend', 'Are you sure you want to delete this item?'),
                                'method' => 'post',
                            ],
                        ])
                        ?>
                    </div>
                </div>
            <?php endif; ?>
            <div class="portlet-body">
                <?= DetailView::widget([
                    'model' => $model,
                    'attributes' => [
                        'id',
                        'name',
                        'description',
                        'created_at',
                        'updated_at',
                        [
                            'attribute' => '',
                            'label' => Yii::t('backend', 'Partners'),
                            'format' => 'raw',
                            'value' => function($model) {
                                $html = '';
                                $partners = $model->partners;
                                if (count($partners)) {
                                    foreach($partners as $index => $partner) {
                                        $html .= ($index == 0)? $partner->name: ', '. $partner->name;
                                    }
                                }
                                return $html;
                            }
                        ]
                    ],
                ]) ?>
            </div>
        </div>
    </div>
</div>