api_public/modules/v1/controllers/SiteController.php
<?php


namespace api_public\modules\v1\controllers;


use api_public\libs\ApiHelper;
use api_public\libs\ApiResponseCode;
use Yii;

class SiteController extends ApiController
{
    public function actionTerms()
    {
        $errorCode = ApiResponseCode::SUCCESS;

        if (Yii::$app->language == 'en') {
            $data = $this->renderPartial('termsEn');
        } else {
            $data = $this->renderPartial('termsMm');
        }

        return ApiHelper::formatResponse(
            $errorCode,
            $data,
            $message
        );
    }
}

api_public/modules/v1/views/feng-shui-horoscope/_seo.php
<?php $this->title = $title; ?>
<?php
$this->registerMetaTag([
    'name' => 'description',
    'content' => $description
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $keywords
]);

$this->registerMetaTag([
    'name' => 'og:locale',
    'content' => 'vi_VN'
]);
$this->registerMetaTag([
    'name' => 'og:site_name',
    'content' => ''
]);
$this->registerMetaTag([
    'name' => 'og:title',
    'content' => $title,
]);
$this->registerMetaTag([
    'name' => 'og:description',
    'content' => $description
]);

?>

<?php
$this->registerLinkTag([
    'title' => $title,
    'rel' => 'canonical',
    // 'type' => 'application/rss+xml',
    'href' => ($url)? $url: Yii::$app->request->getAbsoluteUrl(),
]);?>

api_public/modules/v1/views/feng-shui-horoscope/agesAndColors.php
<?php 
use common\helpers\FengShuiHelper;

$dateInfoArr = FengShuiHelper::getArrayDateInfo($day, $month, $year);
// echo '<pre>';
// print_r($dateInfoArr);die;

?>

<?= $this->render('_seo', [
    'title' => Yii::t('frontend', 'Ages and colors in Fengshui, Find Your Best Personal Feng Shui Colors'),
    'description' => Yii::t('frontend', 'Choose the best personal feng shui colors to strengthen your energy and even attract good luck'),
    'keywords' => 'khmer feng shui age and color, cambodian fengshui, feng shui colors',
]); ?>

<div class="container-fluid">
	
	<?= $this->render('showErrors', [
			'errorArr' => $errorArr, 
		])?>
	<?php if ($formValid): ?>
	<div class="search-info card ">
		<div class="card-body">
			- <span class="label"><?= Yii::t('frontend', 'Thân chủ');?>:</span> <span class="highlight"><?= ($gender == 1)? Yii::t('frontend', 'Nam'): Yii::t('frontend', 'Nữ')?></span>, 
			<?= Yii::t('frontend', 'sinh ngày');?> <span class="highlight"><?= $day. '/'. $month. '/'. $year ?></span>
			<br />
			- <span class="label"><?= Yii::t('frontend', 'Âm lịch');?>:</span> <span class="highlight"><?= date('d/m/Y', strtotime($dateInfoArr['output_am'])) ?></span> - <?= Yii::t('frontend', 'năm');?> <span class="highlight"><?= Yii::t('frontend', $dateInfoArr['can_chi_nam']) ?></span>
			<br />
			- <span class="label"><?= Yii::t('frontend', 'Theo can chi');?>:</span> <?= Yii::t('frontend', 'ngày');?> <span class="highlight"><?= Yii::t('frontend', $dateInfoArr['can_chi_ngay']) ?></span> <?= Yii::t('frontend', 'tháng');?> <span class="highlight"><?= Yii::t('frontend', $dateInfoArr['can_chi_thang']) ?></span> <?= Yii::t('frontend', 'năm');?> <span class="highlight"><?= Yii::t('frontend', $dateInfoArr['can_chi_nam']) ?></span>
			<br />
			- <?= Yii::t('frontend', 'Tuổi âm dương');?>: <span class="highlight"><?= Yii::t('frontend', FengShuiHelper::tuoiAmDuong($year, $gender));?></span>
		</div>
	</div>
	
	<?php if(!$showFull): ?>
		<?= $this->render('viewMoreContent', [
			'contentStatusCode' => $contentStatusCode,
                'contentId' => 'ages_color',
		])?>
		
	<?php else: ?>
		<?php 
		$saoVan =  FengShuiHelper::tinhSaoVan($dateInfoArr['nam_am'], $gender);
		?>
		<div id="ages-and-colors" class="row">
			<div class="col-sm-6">
				
				<div class="card">
				  <div class="card-header">
				    <?= Yii::t('frontend', 'Về Niên mệnh <span class="highlight2">(coi trọng phần này hơn)</span>');?>
				  </div>
				  <div class="card-body">
				  	<div class="card-title highlight"><?= Yii::t('frontend', $saoVan) . ' - '. Yii::t('frontend', FengShuiHelper::$sao_van_ngu_hanh[$saoVan])?></div>
				    <?php 
						$saoVanNguHanh = FengShuiHelper::$sao_van_ngu_hanh[$saoVan]; 
						$colorArr = FengShuiHelper::$menh_color[$saoVanNguHanh]; 
						
						foreach ($colorArr as $key => $colorStr): 
							$arr = explode(',', $colorStr); 

					?>	
						<?php if ($key == 0):?>
							<?= Yii::t('frontend', 'Màu hợp với tuổi');?>
						<?php elseif($key == 1):?>	
							<?= Yii::t('frontend', 'Màu tương sinh (sinh) tuổi');?>
						<?php else: ?>	
							<?= Yii::t('frontend', 'Tuổi tương sinh (sinh) màu');?>
						<?php endif;?>
						<table class="table tb-table" cellpadding="6" cellspacing="5" align="center">
							<tr>
							<?php
								$countColor = count($arr); 
								foreach ($arr as $i => $value): 
							?>
								<?php if ($countColor == 4):?>
									<td width="25%" bgcolor="<?= trim($value)?>">&nbsp;</td>
								<?php else: ?>
									<td width="100%" bgcolor="<?= trim($value); ?>" style="border:1px solid #dee2e6">&nbsp;</td>
								<?php endif; ?>
							<?php endforeach; // mau ?>
							</tr>
						</table>
					<?php endforeach; // tuong sinh ?>
				  </div>
				</div>
			</div>
			<div class="col-sm-6">
				<div class="card">
				  <div class="card-header">
				    <?= Yii::t('frontend', 'Về Mệnh');?>
				  </div>
				  <div class="card-body ">
				  	<div class="card-title highlight"><?= Yii::t('frontend', $dateInfoArr['menh_ngu_hanh']);?></div>
			    	<?php 
						$menhCanChi = $dateInfoArr['menh_theo_can_chi']; 
						$colorArr = FengShuiHelper::$menh_color[$menhCanChi]; 
						
						foreach ($colorArr as $key => $colorStr): 
							$arr = explode(',', $colorStr); 

					?>	
						<?php if ($key == 0):?>
							<?= Yii::t('frontend', 'Màu hợp với tuổi');?>
						<?php elseif($key == 1):?>	
							<?= Yii::t('frontend', 'Màu tương sinh (sinh) tuổi');?>
						<?php else: ?>	
							<?= Yii::t('frontend', 'Tuổi tương sinh (sinh) màu');?>
						<?php endif;?>
						<table class="table tb-table" cellpadding="6" cellspacing="5" align="center">
							<tr>
							<?php
								$countColor = count($arr); 
								foreach ($arr as $i => $value): 
							?>
								<?php if ($countColor == 4):?>
									<td width="25%" bgcolor="<?= trim($value)?>">&nbsp;</td>
								<?php else: ?>
									<td width="100%" bgcolor="<?= trim($value); ?>" style="border:1px solid #dee2e6">&nbsp;</td>
								<?php endif; ?>
								
							
							<?php endforeach; // mau ?>
							</tr>
						</table>
					<?php endforeach; // tuong sinh ?>
				  </div>
				</div>

				

			</div>
		</div>
	<?php endif; // show full ?>
	<?php endif; // form valid ?>
	
</div>

api_public/modules/v1/views/feng-shui-horoscope/ajaxBurmeseAstrologySigns.php
<div class="modal-header">
    <h5 class="modal-title" ><?= Yii::t('frontend', $signInfo['name']); ?></h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div id="modal-body" class="modal-body">
    <?= nl2br($text); ?>
    <div class="clearfix"></div>
</div>
<div class="modal-footer" >
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><?= Yii::t('frontend', 'Đóng'); ?></button>

        <input type="hidden" name="<?= Yii::$app->request->csrfParam; ?>" value="<?= Yii::$app->request->csrfToken; ?>" />
</div>

api_public/modules/v1/views/feng-shui-horoscope/ajaxZodiacalSigns.php
<div class="modal-header">
    <h5 class="modal-title" ><?= Yii::t('frontend', $signInfo['name']). ' ('. $signInfo['birth_date']. ')'; ?></h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div id="modal-body" class="modal-body">
    <?= nl2br($text); ?>
    <div class="clearfix"></div>
</div>
<div class="modal-footer" >
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><?= Yii::t('frontend', 'Đóng'); ?></button>

        <input type="hidden" name="<?= Yii::$app->request->csrfParam; ?>" value="<?= Yii::$app->request->csrfToken; ?>" />
</div>

api_public/modules/v1/views/feng-shui-horoscope/burmeseZodiacSigns.php
<?php
$this->title =  Yii::t('frontend', 'Burmese Zodiac Signs');
\frontend\assets\HomeAsset::register($this);
?>
<!-- service -->
<div id="cung-hoang-dao2" class="service text-center">
    <div class="container">
        <!-- title -->
        <div class="row">
            <div class="col-10 offset-1">
                <div class="info">
                    <a href="#"><img src="/<?= \common\helpers\Helpers::getCurrentThemeName(); ?>/images/icon1.png" alt=""></a>
                </div>
            </div>
        </div>

        <p class="intro"><?= Yii::t('frontend', 'Browse through the signs of astrology here to known how about today?'); ?></p>

        <!-- Burmese zodiacs -->
        <div class="burmese" id="myanmar_zodiac_signs">
            <div class="row">
                <?php $i = 0; ?>
                <?php foreach(Yii::$app->params['burmese_astrology_signs'] as $index => $zodiac):?>
                    <?php $i ++; ?>
                    <div class="col-6">
                        <div class="zodiac zodiac_<?= $index?>" value="<?= $index?>">
                            <a href="javascript:void(0);"><img src="/<?= \common\helpers\Helpers::getCurrentThemeName(); ?>/images/bz-<?= $i ?>.png" alt=""></a>
                            <br>
                            <h6><?= Yii::t('frontend', $zodiac['name'])?></h6>
                        </div>
                    </div>
                <?php endforeach;?>
            </div>
        </div> <!-- /burmese -->

    </div>
</div> <!-- /service -->
<br />
<div class="container text-center">
    <?= $this->render('@app/views/common/horoscopeLink');?>
</div>
<!--  Modal -->
<div class="modal fade" id="cung-modal" tabindex="-1" role="dialog" aria-labelledby="cung-modalLabel" aria-hidden="true" data-keyboard="false">
    <div class="modal-dialog" role="document">
        <div id="modal-content" class="modal-content">

        </div>
    </div>
</div>
<?php if (Yii::$app->request->get('showp') && Yii::$app->user->isGuest): ?>
<?php
// data-backdrop="static"
$this->registerJs( <<< EOT_JS_CODE
    $('#myanmar_zodiac_signs .zodiac:first').click();
EOT_JS_CODE
);
?>
<?php endif; ?>

api_public/modules/v1/views/feng-shui-horoscope/genderPredictor.php
<?php 
use common\helpers\FengShuiHelper;

$dateInfoArr1 = FengShuiHelper::getArrayDateInfo(15, $month1, $year1);
$dateInfoArr2 = FengShuiHelper::getArrayDateInfo($day2, $month2, $year2);

$momAge = ($dateInfoArr1['nam_am'] - $dateInfoArr2['nam_am']);
// echo '<pre>';
// print_r($dateInfoArr2);die;
// print_r($dateInfoArr22);die;


?>
<div class="container-fluid">
	
	<?= $this->render('showErrors', [
			'errorArr' => $errorArr, 
		])?>

	<?php if ($formValid && $view == 1): ?>
		<div class="main-info card ">
			<div class="card-body" style="background: url(/tuvi/images/gender.png) right no-repeat;background-size: contain;">
				- <span class="label"><?= Yii::t('frontend', 'Ngày sinh âm lịch của mẹ');?>:</span> <span class="highlight"><?= date('d/m/Y', strtotime($dateInfoArr2['output_am'])) ?></span> - <?= Yii::t('frontend', 'năm');?> <span class="highlight"><?= Yii::t('frontend', $dateInfoArr2['can_chi_nam']) ?></span>
				<br />
				<br />
				- <span class="label"><?= Yii::t('frontend', 'Tháng thụ thai');?>:</span> <span class="highlight"><?= ($month1) ?></span>
				<br />
				- <span class="label"><?= Yii::t('frontend', 'Tuổi âm lịch của mẹ lúc thụ thai');?>:</span> <span class="highlight"><?= $momAge ?></span>

				
					<br />
					- <?= Yii::t('frontend', 'Dự đoán bạn sẽ sinh bé');?>: 
					<span class="highlight">
						<?= ($showFull)? FengShuiHelper::getGenderFromChart($momAge, $month1): '???'; ?>
					</span>
					
			</div>
		</div>
		<br />
		<?php if(!$showFull): ?>
			<?= $this->render('@app/views/layouts/partials/viewMoreContent', [
				'contentStatusCode' => $contentStatusCode,
                'contentId' => 'gender_predict',
			])?>
			
		<?php else: ?>

			<span class="highlight">History of the chinese gender chart?</span>
			<br />
			<?= Yii::t('frontend', 'Người Trung Quốc cổ đại dự đoán giới tính của em bé dựa theo Kinh Dịch (I Ching), và dựa theo Ngũ hành, và Âm dương bát quái.'); ?>
			<br />
			<?= Yii::t('frontend', 'Truyền thuyết nói rằng, biểu đồ giới tính cổ của Trung Quốc được vua quan nhà Thanh sử dụng để lựa chọn sinh con trai cho dòng tộc. Một câu truyện khác nói rằng biểu đồ này được tìm thấy trong một ngôi mộ Hoàng Gia cổ đại.')?>
			<br />
			<?= Yii::t('frontend', 'Nhiều người cho rằng biểu đồ này chính xác tới 90%. Bạn có thể tham khảo thêm biểu đồ bên dưới để dự đoán giới tính của bé.');?>
			<br />
			<br />
			<img class="img img-fluid" width="100%" src="/tuvi/images/chinese-gender-chart.png" />
			<br />
		<?php endif; // show full ?>
	<?php endif; // form valid ?>
	
</div>
<br />

api_public/modules/v1/views/feng-shui-horoscope/horoscopeLink.php
<?php
use yii\helpers\Url;
use common\helpers\Helpers;
?>
<ul class="luban">
<li><a class="" href="<?= Url::to(['feng-shui-horoscope/luban-ruler']); ?>">
	<img class="tuvi-icon" src="/<?= Helpers::getCurrentThemeName() ?>/images/ruler.png" />
	<?= Yii::t('frontend', 'Luban Ruler (Free)');?></a></li>

	<li><a class="" href="<?= Url::to(['feng-shui-horoscope/burmese-zodiac-signs']); ?>">
	<img class="tuvi-icon" src="/<?= Helpers::getCurrentThemeName() ?>/images/horos-icon.png"><?= Yii::t('frontend', 'Burmese Zodiac Signs');?></a></li>
    <li><a class="" href="<?= Url::to(['feng-shui-horoscope/zodiac-signs']); ?>">
            <img class="tuvi-icon" src="/<?= Helpers::getCurrentThemeName() ?>/images/horos-icon.png"><?= Yii::t('frontend', 'Astrology Zodiac Signs');?></a></li>
<li><a class="" href="<?= Url::to(['feng-shui-horoscope/sim-feng-shui']); ?>">
	<img class="tuvi-icon" src="/<?= Helpers::getCurrentThemeName() ?>/images/sim.png" />
	<?= Yii::t('frontend', 'SIM Feng Shui');?>
		
	</a></li>
<li><a class="" href="<?= Url::to(['feng-shui-horoscope/couple']); ?>">
	<img class="tuvi-icon" src="/<?= Helpers::getCurrentThemeName() ?>/images/love.png" />
	<?= Yii::t('frontend', 'Feng Shui for couples');?>
	</a></li>
<li><a class="" href="<?= Url::to(['feng-shui-horoscope/gender-predictor']); ?>">
	<img class="tuvi-icon" src="/<?= Helpers::getCurrentThemeName() ?>/images/baby.png" />
	<?= Yii::t('frontend', 'Boy or girl? Gender predictor');?></a></li>
<li><a class="" href="<?= Url::to(['feng-shui-horoscope/ages-and-colors']); ?>">
	<img class="tuvi-icon" src="/<?= Helpers::getCurrentThemeName() ?>/images/love.png" />
	<?= Yii::t('frontend', 'Ages and colors in Feng Shui');?></a></li>

</ul>

api_public/modules/v1/views/feng-shui-horoscope/showErrors.php
<?php $view = Yii::$app->request->get('view', null); ?>
<?php if($view == 1 && count($errorArr)): ?>
	<div class="alert alert-warning" role="alert">
	<?php foreach($errorArr as $err): ?>
		<div class="err-msg"><?= $err; ?></div>
	<?php endforeach; ?>
	
	</div>
<?php endif;?>

api_public/modules/v1/views/feng-shui-horoscope/viewMoreContent.php
<?php 
use yii\helpers\Url;
?>
<?php if ($contentStatusCode != 1): ?>
<br />
<div class="<?= ($divClass)? $divClass: 'view-more'?>">
    <?php // \common\helpers\Helpers::getTextByContentStatus($contentStatusCode); ?>
    <?= Yii::t('frontend', 'Know your future, your luck with MyZartar!') ?>
    <br />
    <?= Yii::t('frontend', 'On your first time registration, you can use service for <b>01 week FREE</b> of charge and will get 01 Lucky Code for Myluck (<a target="_blank" href="{url}">www.myluck.asia</a>) where you can get the chance to be a winner of daily and monthly amazing cash prizes up to 600,000Ks.', [
        'url' => 'http://myluck.asia'
    ]) ?>
    <br />
    <br />
    <br />
    <br />
    <?php if(Yii::$app->language == 'en'): ?>
        <center>Terms & Conditions</center>
        1. By choosing package, you agree to our terms and conditions<br />
        2. You are subscribing to an annual subscription and you will be charged in installments of 499ks/week until you unsubscribe.<br />
        3. T&C will not apply if you unsubscribed or do not recharge for 30 consecutive days.<br />
        4. If you do not recharge for 30 consecutive days, your subscription will be cancelled automatically.<br />
        5. To unsubscribe, send OFF to 599 or dial *599#.<br>
        6. For more details, access link <a style="color:gold" href="<?= Url::to(['site/terms'])?>" target="_blank">TERMS & CONDITIONS</a><br>
    <?php else: ?>
        <center>စည်းမျဉ်းစည်းကမ်းများ</center>

        ၁။ ပက်ကေ့ရွေးချယ်ခြင်းအားဖြင့် ကျွနု်ပ်တို့၏ စည်းမျဉ်းစည်းကမ်းများနှင့် အခြေအနေကိုသဘောတူသည်။
        <br>
        ၂။ သင်သည်နှစ်စဉ်ကြေးသွင်းနေပြီး ဝန်ဆောင်မှုကို ပယ်ဖျက်ပြီးသည်အထိ တစ်ပါတ်လျှင် ၄၉၉ကျပ် ကျသင့်မည်ဖြစ်ပါသည်။
        <br>
        ၃။ အကယ်၍ သင်သည် ဝန်ဆောင်မှုကိုပယ်ဖျက်ပါက သို့မဟုတ် ရက်ပေါင်း၃၀ ဆက်တိုက်မကောက်ခံပါက ဤစည်းကမ်းများသည် အသုံးမဝင်တော့ပါ။
        <br>
        ၄။ ရက်ပေါင်း ၃၀ဆက်တိုက်ငွေမသွင်းပါက သင်၏စာရင်းပေးသွင်းခြင်းကို အလိုအလျှောက်ဖျက်သိမ်းလိမ့်မည်။
        <br>
        ၅။ အချိန်မရွေးပယ်ဖျက်လိုလျှင် 599 သို့ OFF ဟုပို့ပါ။
        <br>
        ၆။ အသေးစိတ်သိလိုလျှင် လင့်ကို ဝင်ပါ။ <a style="color:gold" href="<?= Url::to(['site/terms'])?>" target="_blank">TERMS & CONDITIONS</a>
        <br>
    <?php endif; ?>
    </div>
</div>
<br />

<?php endif; ?>

api_public/modules/v1/views/feng-shui-horoscope/zodiacSigns.php
<?php
$this->title = Yii::t('frontend', '12 Zodiac Signs');
\frontend\assets\HomeAsset::register($this);
?>

<div id="cung-hoang-dao" class="service text-center">
    <div class="container">
        <!-- title -->
        <div class="row">
            <div class="col-10 offset-1">
                <div class="info">
                    <a href="#"><img src="/<?= \common\helpers\Helpers::getCurrentThemeName(); ?>/images/icon2.png" alt=""></a>
                </div>
            </div>
        </div>

        <p class="intro">
            <?= Yii::t('frontend', 'No matter what your Sun sign, we are all affected by the 12 signs of the zodiac, as the Sun and other planets cycle through the horoscope over the course of a year. Browse through the signs of astrology here to known how about today?'); ?>
        </p>

        <!-- 12 zodiacs -->
        <div class="zodiac12">
            <div class="row">
                <?php $i = 0; ?>
                <?php foreach(Yii::$app->params['zodiacal_signs'] as $index => $zodiac):?>
                    <?php $i ++; ?>
                    <div class="col-6">
                        <div class="zodiac zodiac_<?= $index; ?>" value="<?= $index; ?>">
                            <a href="javascript:void(0)"><img src="/<?= \common\helpers\Helpers::getCurrentThemeName(); ?>/images/12-<?= $i ?>.png" alt=""></a>
                            <br>
                            <h6><?= Yii::t('frontend', $zodiac['name'])?><br /><?= Yii::t('frontend', '('. $zodiac['birth_date'].')')?></h6>
                        </div>

                    </div>
                <?php endforeach;?>
            </div>
        </div> <!-- /12 zodiacs -->
    </div>
</div> <!-- /service -->
<div class="container text-center">
    <?= $this->render('@app/views/common/horoscopeLink');?>
</div>

<!--  Modal -->
<div class="modal fade" id="cung-modal" tabindex="-1" role="dialog" aria-labelledby="cung-modalLabel" aria-hidden="true" data-keyboard="false">
    <div class="modal-dialog" role="document">
        <div id="modal-content" class="modal-content">

        </div>
    </div>
</div>
<?php if (Yii::$app->request->get('showp') && Yii::$app->user->isGuest): ?>
<?php
// data-backdrop="static"
$this->registerJs( <<< EOT_JS_CODE
    $('#cung-hoang-dao .zodiac:first').click();
EOT_JS_CODE
);
?>
<?php endif; ?>